
import sys
import os
import random
import psycopg2
from datetime import datetime, timedelta
from werkzeug.security import generate_password_hash

# Add parent directory to path to import modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from repository.db import get_db_connection

def seed_team_data():
    conn = get_db_connection()
    # No "with conn.cursor()", we manage transaction manually or use commit
    cur = conn.cursor()
    
    print("\n🌱 Seeding Team Data for User: nadeshgracious001@gmail.com\n")
    
    try:
        # 1. Get Manager ID
        cur.execute("SELECT id FROM users WHERE email = 'nadeshgracious001@gmail.com'")
        manager = cur.fetchone()
        
        if not manager:
            print("❌ Manager not found!")
            return

        manager_id = manager['id']
        print(f"✅ Found Manager ID: {manager_id}")

        # 2. Create Dummy Employees
        employees = [
            ("Alice Smith", "alice.smith@example.com", "Analyst"),
            ("Bob Jones", "bob.jones@example.com", "Developer"),
            ("Charlie Brown", "charlie.brown@example.com", "Designer"), 
            ("Diana Prince", "diana.prince@example.com", "Engineer")
        ]
        
        created_employees = []
        
        for name, email, job_role in employees:
            # Check if exists
            cur.execute("SELECT id FROM users WHERE email = %s", (email,))
            existing = cur.fetchone()
            
            if existing:
                emp_id = existing['id']
                # Update manager if needed
                cur.execute("UPDATE users SET manager_id = %s, role = 'employee', job_role = %s WHERE id = %s", (manager_id, job_role, emp_id))
                created_employees.append(emp_id)
                print(f"🔄 Updated existing employee: {name}")
            else:
                cur.execute("""
                    INSERT INTO users (username, email, password_hash, role, manager_id, job_role, created_at)
                    VALUES (%s, %s, %s, 'employee', %s, %s, NOW())
                    RETURNING id
                """, (name, email, generate_password_hash("password123"), manager_id, job_role))
                emp_id = cur.fetchone()['id']
                created_employees.append(emp_id)
                print(f"✅ Created new employee: {name}")

        # 3. Generate Activity (Tasks & Delays) for each employee
        reasons = [
            "Unexpected bug in production", 
            "Awaiting client feedback", 
            "Technical debt cleanup", 
            "Server outage", 
            "Requirements changed"
        ]
        
        for emp_id in created_employees:
            # Create 5-8 Tasks
            for i in range(random.randint(5, 8)):
                is_delayed = random.choice([True, False, False]) # 33% chance of delay
                status = 'Delayed' if is_delayed else random.choice(['Completed', 'Pending'])
                
                cur.execute("""
                    INSERT INTO tasks (title, description, assigned_to, created_by, status, priority, deadline, estimated_minutes)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                """, (
                    f"Team Task {i+1}", 
                    "Generated by seeder", 
                    emp_id, 
                    manager_id, 
                    status, 
                    random.choice(['High', 'Medium', 'Low']),
                    datetime.now() + timedelta(days=random.randint(1, 7)),
                    random.randint(30, 240)
                ))
                task_id = cur.fetchone()['id']
                
                # If delayed, add delay record
                if is_delayed:
                    score = random.randint(40, 95)
                    risk = "Low" if score > 80 else ("Medium" if score > 60 else "High")
                    
                    cur.execute("""
                        INSERT INTO delays (task_id, user_id, reason_text, score_authenticity, score_avoidance, risk_level, delay_duration, ai_feedback, ai_analysis_json)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                    """, (
                        task_id,
                        emp_id,
                        random.choice(reasons),
                        score,
                        100 - score,
                        risk,
                        random.randint(600, 7200),
                        "Generated by Team Seeder",
                        '{"sentiment": "neutral"}'
                    ))
        
        conn.commit()
        print("\n🎉 Team Data Seeded Successfully!")
        print(f"   - {len(created_employees)} Employees assigned to Manager {manager_id}")
        print("   - Tasks and Delays generated.")
        
    except Exception as e:
        conn.rollback()
        print(f"❌ Error seeding team data: {e}")
        import traceback
        traceback.print_exc()
    finally:
        conn.close()

if __name__ == "__main__":
    seed_team_data()
