
import os
import sys
import random
from datetime import datetime, timedelta

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from repository.db import execute_query
from database.connection import DatabaseConnection

def seed_analytics_data():
    print("🚀 Starting Analytics Data Seeding...")
    
    try:
        # Initialize DB
        DatabaseConnection.initialize_pool(min_conn=1, max_conn=2)
        
        # 1. Get Target User
        email = "nadeshgracious001@gmail.com"
        user = execute_query("SELECT id FROM users WHERE email = %s", (email,), fetch=True)
        
        if not user:
            print(f"❌ User {email} not found! Please register/login first.")
            return
            
        user_id = user[0]['id']
        print(f"✅ Found User ID: {user_id}")
        
        # 2. task templates
        task_templates = [
            ("Complete UI Analysis", "Review dashboard layouts", "High"),
            ("Database Optimization", "Add indexes to tasks table", "High"),
            ("User Interview", "Gather requirements from marketing", "Medium"),
            ("Fix Login Bug", "Resolve session timeout issue", "High"),
            ("Update Documentation", "Write API docs", "Low"),
            ("Weekly Team Sync", "Discuss project roadmap", "Medium"),
            ("Deploy to Staging", "Release v1.2 candidate", "High"),
            ("Code Review", "Review PR #42", "Medium"),
            ("Security Audit", "Check for SQL injection vulnerabilities", "High"),
            ("Email Template Update", "Refresh newsletter styles", "Low")
        ]
        
        statuses = ['Completed', 'Pending', 'Delayed']
        
        created_count = 0
        delay_count = 0
        
        print("🌱 Seeding Tasks...")
        
        for _ in range(15): # Create 15 random tasks
            title, desc, priority = random.choice(task_templates)
            status = random.choice(statuses)
            
            # Random dates within last 30 days
            days_ago = random.randint(0, 30)
            created_at = datetime.now() - timedelta(days=days_ago)
            deadline = created_at + timedelta(days=random.randint(1, 5))
            estimated_minutes = random.randint(30, 480) # 30 mins to 8 hours
            
            # Create Task
            task_query = """
                INSERT INTO tasks (title, description, priority, status, assigned_to, created_at, deadline, estimated_minutes)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING id
            """
            result = execute_query(task_query, (title + f" {random.randint(1,99)}", desc, priority, status, user_id, created_at, deadline, estimated_minutes), fetch=True)
            task_id = result[0]['id']
            created_count += 1
            
            # If delayed, add delay record
            if status == 'Delayed':
                reasons = ["Technical Issue", "Personal Emergency", "Identify Gap", "External Blocker"]
                reason = random.choice(reasons)
                
                # Random delay duration
                delay_duration = random.randint(120, 3600)
                score = random.randint(50, 95)
                risk = "Low" if score > 80 else ("Medium" if score > 60 else "High")
                
                delay_query = """
                    INSERT INTO delays (task_id, user_id, reason_text, reason_audio_path, score_authenticity, score_avoidance, risk_level, ai_feedback, ai_analysis_json, delay_duration, proof_path)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """
                # Use JSON string for ai_analysis_json
                ai_analysis = '{"sentiment": "neutral", "keywords": ["unexpected"]}'
                
                execute_query(delay_query, (
                    task_id, 
                    user_id, 
                    reason,        # reason_text
                    None,          # reason_audio_path
                    score,         # score_authenticity
                    100 - score,   # score_avoidance
                    risk,          # risk_level
                    "Generated by seeding script", # ai_feedback
                    ai_analysis,   # ai_analysis_json
                    delay_duration,# delay_duration 
                    None           # proof_path
                ), fetch=False)
                delay_count += 1
                
        print(f"✅ Created {created_count} tasks.")
        print(f"✅ Created {delay_count} delay records.")
        
        # 3. Trigger Optimization to refresh views
        print("\n🔄 Refreshing Analytics Views...")
        # Since we can't easily import the optimization script's main, we'll just run the key part or rely on the user to run it.
        # But let's try to run the refresh query directly here.
        
        try:
             execute_query("REFRESH MATERIALIZED VIEW user_analytics_summary", fetch=False)
             print("✅ Materialized View Refreshed")
        except Exception as e:
             print(f"⚠️ Could not refresh view (might be a table or not exist): {e}")

        print("\n🎉 Seeding Complete! Please refresh your dashboard.")
            
    except Exception as e:
        print(f"❌ Error seeding data: {e}")

if __name__ == "__main__":
    seed_analytics_data()
